version: '3.8'

networks:
    api-dev:
        driver: bridge

services:
    rentapi:
        image: rentservice
        build:
            context: .
            dockerfile: RentService\Web\Dockerfile
        ports:
            - 80:80
            - 443:443
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=dev
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
            - ~/.aspnet/https:/https:ro